=== davan690/r-for-news-data/1654_newsbooks/newsbookDoc.dtd
<!-- dialogueDoc DTD -->

<!ELEMENT	newsbookDoc		( newsbookHeader, newsbookText )			>

<!ATTLIST	newsbookDoc
		id			CDATA					#REQUIRED	>


<!-- the Header -->


<!ELEMENT	newsbookHeader		( title )						>

<!ELEMENT	title			( #PCDATA )						>


<!-- the main body -->

<!ELEMENT	newsbookText		( p | head | poem | table | hr | pb | img | note )*	>



<!ELEMENT	p			( #PCDATA | i | go | em | reg | unclear | pb | ptr
					| img )*						>

<!ELEMENT	head			( #PCDATA | i | go | em | reg | unclear | pb | ptr )*	>
<!ATTLIST	head
		level			( 1 | 2 | 3 )				#REQUIRED	>


<!ELEMENT	note			( p | head | poem | table | hr | pb | img | note )*	>
<!ATTLIST	note
		place			( side | foot | end | unspec )		"unspec"
		id			CDATA					#REQUIRED	>

<!ELEMENT	i			( #PCDATA | em | reg | unclear | pb )*			>

<!ELEMENT	go			( #PCDATA | em | reg | unclear | pb )*			>

<!ELEMENT	em			( #PCDATA | reg | unclear )*				>

<!ELEMENT	unclear			( #PCDATA | i | go | em | reg | pb )*			>
<!ATTLIST	unclear
		extent			CDATA					#IMPLIED	>

<!ELEMENT	reg			( #PCDATA )						>
<!ATTLIST	reg
		orig			CDATA					#REQUIRED	>



<!ELEMENT	hr			EMPTY							>
<!ELEMENT	pb			EMPTY							>
<!ATTLIST	pb
		n			CDATA					#REQUIRED	>
<!ELEMENT	img			EMPTY							>
<!ATTLIST	img
		src			CDATA					#IMPLIED
		alt			CDATA					#REQUIRED	>
<!ELEMENT	ptr			EMPTY							>
<!ATTLIST	ptr
		target			CDATA					#REQUIRED	>





<!ELEMENT	poem			( stanza | pb | head )*					>
<!ATTLIST	poem
		basefont		( roman | italic | gothic )		#REQUIRED	>

<!ELEMENT	stanza			( line, ( line | pb )* )				>

<!ELEMENT	line			( #PCDATA | i | go | em | reg | unclear | pb | ptr )*	>

<!ELEMENT	table			( tr+ )							>
<!ELEMENT	tr			( td+ )							>
<!ELEMENT	td			( p | h1 | h2 | h3 | poem | img	)			>
<!ATTLIST	td
		colspan			CDATA					"1"
		rowspan			CDATA					"1"		>

<!-- if a td is empty, tag it as <td><p></p></td> or <td><p>&nbsp;</p></td> -->



<!-- Entities used in corpus are either (a) numeric Unicode entities, or (b) -->
<!-- entities drawn from (X)HTML. So the W3C's entity declarations are used.    See http://www.w3.org/2003/entities/xhtml1doc/overview.html -->


       <!ENTITY % xhtml1-lat1 SYSTEM
         "xhtml1-lat1.ent"
       >
       %xhtml1-lat1;

       <!ENTITY % xhtml1-special SYSTEM
         "xhtml1-special.ent"
       >
       %xhtml1-special;

       <!ENTITY % xhtml1-symbol SYSTEM
         "xhtml1-symbol.ent"
       >
       %xhtml1-symbol;

=== davan690/r-for-news-data/1654_newsbooks/PerfOcc$1.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE newsbookDoc SYSTEM "newsbookDoc.dtd" >

<newsbookDoc id="PerfOcc$1">
<newsbookHeader>
<title>Perfect Occurrences, issue $1</title>
</newsbookHeader>
<newsbookText>
<pb n="0" />

<head level="1">Perfect Occurrences</head>
<head level="3">Faithfully communicating,</head>

<p><i>A great Combat fought in Scotland between Sir <em>George Monroe</em>, and the Earl of <em>Glencarn</em>, for their <reg orig="plundring">plundering</reg> one another; in which combat <em>Monro</em> had his right hand cut off, and a great cut in the forehead, <em>Glencarn</em> was also cut in the head. Four propositions of the Queen of <em>Sweden</em> to the Prince. A List of the names of the Scottish party, who are exempted out of the Ordinance for Grace and Pardon, and a <reg orig="yeerly">yearly</reg> allowance given to their wives and children out of their <reg orig="Husbands">Husbands'</reg> and <reg orig="Fathers">Fathers'</reg> estates. Also an Order for new Farthings, A List of the Dutch Prizes taken, With a Proclamation of the peace concluded on between this Commonwealth, and that of the United Provinces of the Netherlands.</i></p>

<hr />
<p>From <em>Friday</em> April 21. to <em>Friday</em> April. 28. 1654.</p>
<hr />

<head level="3"><i>Beginning Friday April 21.</i></head>

<p>By Letters this day from <em><reg orig="Edenburgh">Edinburgh</reg></em>, we are advertised, that our small Garrisons <reg orig="neer">neer</reg> <reg orig="Sterling">Stirling</reg> have fallen with success into the <reg orig="enemies">enemy's</reg> quarters, and brought away divers prisoners, and amongst the rest a party from Bubannon marched into the parish of Strablain, where Capt. Cunningham and Capt. Edmiston were levying of horse and foot, took Capt. Cunningham, and very narrowly <reg orig="mist">missed</reg> cap. Edmiston.</p><pb n="1" />

<head level="3"><i>Saturday April 22.</i></head>

<p>The good service this Day was advertised by our parties in the North of Scotland, against the Forces of Gen. <em>Middleton</em> where some parties of ours have met with several parties of theirs, and routed them, <reg orig="kiled">killed</reg> some, and took some eminent persons prisoners, by whom it is confessed that <em>Middleton</em> hath called several <reg orig="Counselr">Councils</reg> of war, and was not at that time resolved whether to fight, or to retire to the protection of the inhospitable Mountains, one of the two by this time he hath done.</p>

<p>It is certified that one of our <reg orig="Frigots">Frigates</reg> who Convoyed some <reg orig="Amunition">Ammunition</reg>, and divers Merchant ships to <em>Leith</em>, <reg orig="war">was</reg> set upon by the <reg orig="dutch">Dutch</reg>, and after a furious Fight boarded, and carried away.</p>

<p>There is a Report also, that they took some other ships that were with her.</p>

<p>It is certified also that the constant Warwick had no sooner put off from <em><reg orig="Plimouth">Plymouth</reg></em> where she was new tallowed, but she met with a <em>Picaroon</em> belonging to brest, and <reg orig="immediatly">immediately</reg> <reg orig="surprized">surprised</reg>, she carried but four guns but was an excellent <reg orig="saylor">sailor</reg>.</p>

<p>One of our <reg orig="Frigots">Frigates</reg> called the <reg orig="paul">Paul</reg> hath <reg orig="takeen">taken</reg> two <em>French</em> ships, and sent them to Falmouth. A Poet belonging to the Court of France hath been taken, and soundly punished for making some Verses <reg orig="a gainst">against</reg> the titular King of Scots, and his Brother the Duke of York.</p>

<p>The Ordinance was this Day extant for suspending the proceeding of the Judges for the Relief of Creditors, and poor prisoners until the 15 day of <em>May</em> next ensuing.</p>

<p>The Resident in <em>England</em> for the Duke of <em>Guelders</em>, who is also Count of Egmant, was yesterday in gallant Equipage attended to <reg orig="White hall">Whitehall</reg>, where he had Audience<pb n="2" /> with great respect from his Highness.</p>

<head level="3"><i><reg orig="Munday">Monday</reg> 24.</i></head>

<p>By Letters by the Post from <em>Scotland</em>, it was this Day advertised, that Major Gen: <em>Dyal</em>, who lately came over with Gen: <em>Middleton</em>, hath besieged <em>Senclair</em> Castle, with a party of 400 Foot, and 800 horse, but the place being made strong both by <unclear>Air</unclear>, and Nature, and well victualled, they do not much fear the assaults of, their <reg orig="Enimies">Enemies</reg>,</p>

<p>The Armies on both sides are preparing to receive each other, and Col. <em>Morgan</em> has drained <reg orig="Innerness">Inverness</reg> to <reg orig="joyn">join</reg> with those forces which he brought from Aberdeen, so that he lies with about 1200 Horse and Dragoons, and 2000 Foot, betwixt the Enemy and the passes they must needs through, if they intend to move out of the North corner; so they <reg orig="wil">will</reg> be compelled to fight, and 'tis said, they are resolved, there being no way left them to avoid it, but through such <reg orig="inaccesable">inaccessible</reg> bounds as <reg orig="tis">'tis</reg> impossible for their horse to march that way, and very difficult for their Foot,</p>

<p><em>From Dalkeith</em>, April 19. thus. Notwithstanding the hand of God is so eminently seen in destroying these rude people, and that they are no sooner <reg orig="gatherd">gathered</reg> together, but they are <reg orig="scatered">scattered</reg>, yet they are <reg orig="stil">still</reg> Breaking forth in the Lowlands, and amongst others, the Earl of <em>Salkik</em> second son to the <reg orig="Marquess">Marques</reg> of <em>Douglass</em>, started out of the other day, and went away from about <em>Boggehall</em> with 60 Horse, and this week about 40 Englishmen are got to the Hills under the Command of an Irishman. Col. <em>Daniel</em>, Capt. <em>Elsmare</em>, and others have lately met with divers of the Rebels, so that <reg orig="tha">the</reg> prisoners begin now so to fill that the only way to ease the Commonwealth of their charge will be to send these Idle people to <reg orig="Barbadoes">Barbados</reg> to work for their living, which <reg orig="wil">will</reg> be done very suddenly.</p><pb n="3" />

<head level="3"><i>Tuesday April 25.</i></head>

<p>This day the Proclamation for peace was Proclaimed by 12 Trumpets, and 4 Heralds at Arms, first at <reg orig="White hall">Whitehall</reg> before his Highness the Lord Protector, and his <reg orig="Coucil">Council</reg> (both Courts being full of people)</p>

<head level="3">By the Lord Protector.</head>

<head level="3">A Proclamation of the peace made between this <reg orig="Common-wealth">Commonwealth</reg>, and that of the <reg orig="Vnited">United</reg> provinces of the Netherlands.</head>

<p>His <reg orig="Highnesse">Highness</reg> the Lord Protector of the <reg orig="Common wealth">Commonwealth</reg> of <em>England, Scotland</em> and <em>Ireland</em> considering how necessary it is, not only to preserve peace and Quiet at home, but as far as in him lies, to live in Amity and friendship with his neighbours, hath by the blessing of God, with the advice of his Council, made and concluded a peace, <reg orig="Vnion">Union</reg> and Confederation to continue <reg orig="for ever">forever</reg>, between this Commonwealth of the one part, and of the <reg orig="Vnited">United</reg> provinces of the Low Countries of the other part; their Lands, Countries, Cities, Towns, Dominions, <reg orig="Teritories">Territories</reg>, Places and people, by Sea, Land, <reg orig="Fresh waters">Freshwaters</reg> and elsewhere; By the which peace it is agreed, that all Enmity, Hostility, Discord and War between the said Commonwealths, their people and Subjects shall cease, and all injuries and wrongs whatsoever done since the 18 &amp; 23. of <em>May</em>, One thousand six hundred fifty two, shall cease and be forgotten, except such Depredations as shall be committed by either side in these Seas after twelve days, from the date of these presents, &amp;c. For want of room, I refer you to the printed copy for the rest.</p>

<p>This day are come out new farthings, weighing a quarter of an ounce fine pewter, which is but the price of new pewter; that so the people may never hereafter fear to <reg orig="loose">lose</reg> much by them; with the Harp of one side, and a <reg orig="Crosse">Cross</reg> on the other, with T.K. above it.</p><pb n="4" />

<p>This day passed an Ordinance of pardon and Grace to the people of Scotland after 1 May 1654. except the persons following, and their estates.</p>

<p><em>Henrietta Maria</em>, late Queen. <em><reg orig="Charls">Charles</reg> Stuart</em> her son. <em><reg orig="Iames">James</reg> Stuart</em> her son. <em>James</em> late Duke <em>Hamilton</em>. <em>William</em> late Duke <em>Hamilton</em>. Earl <em>Craford Linsey</em>. Earl <em>Calender</em>. Earl <em><reg orig="Marshal">Marshall</reg></em>. Earl <em>Kelly</em>. Earl <em>Lauderdale</em>: Earl <em>London</em>. Earl <em>Seaforth</em>, Earl <em>Athol</em>, Viscount <em>Kenmore</em>, Lord <em>Lorn</em>, Lord <em>Machlin</em>, Lord <em>Montgomery</em>, Lord <em>Spynie</em>, Lord <em>Crunston</em>, Major Gen. <em>Dalyel</em>, Lieut. Gen. <em>Middleton</em>, Viscount <em>Newburgh</em>, Lord <em>Bargany</em>, Sir <em>Tho. Thomson</em>, Laird of <em>Womut</em>, Laird <em>Napier</em>, Earl of <em>Glencahn</em>. Divers others are fined to pay certain sums of moneys, <em>David Leshly</em> 4000 li. Marquis <em>Douglas</em>, 100 l. and several other sums.</p>

<p><i>A <reg orig="yeerly">yearly</reg> allowance given to their wives and children out of their <reg orig="Husbands">Husband's</reg> and <reg orig="fathers">fathers</reg> estates.</i></p>
